#!/bin/sh
# cfscan dev link: point the `cfscan` command at THIS folder, live.
#
# install.sh copies the package into ~/.local/share/cfscan/lib, so every edit
# needs ./update.sh before the terminal sees it. This script instead writes a
# launcher that imports the package straight from this folder, so an edit is
# live on the next run - no copy step, ever.
#
# Reverse it with ./install.sh (back to the copied install) at any time.
set -eu

SOURCE="$(cd "$(dirname "$0")" && pwd)"
BIN_DIR="${HOME}/.local/bin"
TARGET="${BIN_DIR}/cfscan"
LIB="${HOME}/.local/share/cfscan/lib/cfscan"

PYTHON="${CFSCAN_PYTHON:-$(command -v python3 || true)}"

echo "cfscan dev link"
echo "---------------"

if [ -z "${PYTHON}" ]; then
    echo "ERROR: python3 was not found on your PATH." >&2
    exit 1
fi

VERSION="$("${PYTHON}" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
if [ "$(printf '%s\n' "3.9" "${VERSION}" | sort -V | head -n 1)" != "3.9" ]; then
    echo "ERROR: Python 3.9 or newer is required (found ${VERSION})." >&2
    exit 1
fi

if [ ! -f "${SOURCE}/cfscan/cli.py" ]; then
    echo "ERROR: run this script from the cfscan project folder." >&2
    exit 1
fi

mkdir -p "${BIN_DIR}"

# PYTHONDONTWRITEBYTECODE keeps __pycache__ folders out of the working tree, so
# a live link never leaves build noise next to the sources you are editing.
cat > "${TARGET}" <<EOF
#!/bin/sh
# cfscan launcher - DEV LINK (generated by dev-link.sh - safe to delete).
#
# This runs the package straight from the project folder below, so every edit
# is live on the next run. Run that folder's ./install.sh to go back to a
# copied install.
CFSCAN_DEV_SOURCE="${SOURCE}"
if [ ! -f "\${CFSCAN_DEV_SOURCE}/cfscan/cli.py" ]; then
    echo "cfscan: the linked project folder is gone:" >&2
    echo "  \${CFSCAN_DEV_SOURCE}" >&2
    echo "Move it back, or run install.sh from wherever the project lives now." >&2
    exit 69
fi
exec env \\
    PYTHONPATH="\${CFSCAN_DEV_SOURCE}\${PYTHONPATH:+:\${PYTHONPATH}}" \\
    PYTHONDONTWRITEBYTECODE=1 \\
    CFSCAN_DEV_SOURCE="\${CFSCAN_DEV_SOURCE}" \\
    "${PYTHON}" -m cfscan "\$@"
EOF
chmod 755 "${TARGET}"

echo "Using Python ${VERSION} at ${PYTHON}"
echo
"${TARGET}" --version
echo
echo "Linked:"
echo "  launcher : ${TARGET}"
echo "  sources  : ${SOURCE}/cfscan  (live - edits need no update step)"
if [ -e "${LIB}" ]; then
    echo
    echo "Note: the copied install at"
    echo "  ${LIB}"
    echo "is no longer used. It is harmless; './install.sh' would make it the"
    echo "active copy again, and './uninstall.sh' removes it."
fi
echo
case ":${PATH}:" in
    *":${BIN_DIR}:"*)
        echo "Run 'cfscan' - it now runs the code in this folder."
        ;;
    *)
        echo "${BIN_DIR} is not in your PATH yet. Add this to ~/.zshrc:"
        echo
        echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
        echo
        echo "Until then, start it with: ${TARGET}"
        ;;
esac
