#!/bin/sh
# cfscan installer.
#
# Copies the cfscan package into ~/.local/share/cfscan/lib and creates the
# ~/.local/bin/cfscan launcher. Nothing outside your home directory is touched
# and no administrator rights are needed.
set -eu

PREFIX="${HOME}/.local"
LIB="${PREFIX}/share/cfscan/lib"
BIN_DIR="${PREFIX}/bin"
TARGET="${BIN_DIR}/cfscan"
SOURCE="$(cd "$(dirname "$0")" && pwd)"

PYTHON="${CFSCAN_PYTHON:-$(command -v python3 || true)}"

echo "cfscan installer"
echo "----------------"

if [ -z "${PYTHON}" ]; then
    echo "ERROR: python3 was not found on your PATH." >&2
    echo "Install Python 3.9 or newer (for example: brew install python)." >&2
    exit 1
fi

VERSION="$("${PYTHON}" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
echo "Using Python ${VERSION} at ${PYTHON}"

if [ "$(printf '%s\n' "3.9" "${VERSION}" | sort -V | head -n 1)" != "3.9" ]; then
    echo "ERROR: Python 3.9 or newer is required (found ${VERSION})." >&2
    exit 1
fi

if [ ! -f "${SOURCE}/cfscan/cli.py" ]; then
    echo "ERROR: run this script from the cfscan project folder." >&2
    exit 1
fi

mkdir -p "${LIB}" "${BIN_DIR}"

rm -rf "${LIB}/cfscan"
cp -R "${SOURCE}/cfscan" "${LIB}/cfscan"
find "${LIB}/cfscan" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true

cat > "${TARGET}" <<EOF
#!/bin/sh
# cfscan launcher (generated by install.sh - safe to delete).
CFSCAN_LIB="\${HOME}/.local/share/cfscan/lib"
exec env PYTHONPATH="\${CFSCAN_LIB}\${PYTHONPATH:+:\${PYTHONPATH}}" "${PYTHON}" -m cfscan "\$@"
EOF
chmod 755 "${TARGET}"

"${TARGET}" --version

echo
echo "Installed:"
echo "  launcher : ${TARGET}"
echo "  package  : ${LIB}/cfscan"
echo
case ":${PATH}:" in
    *":${BIN_DIR}:"*)
        echo "Run 'cfscan' to open the menu."
        ;;
    *)
        echo "${BIN_DIR} is not in your PATH yet. Add this line to your shell"
        echo "profile (~/.zshrc) and open a new terminal:"
        echo
        echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
        echo
        echo "Until then you can start it with: ${TARGET}"
        ;;
esac
echo
echo "First start creates ~/.config/cfscan/config.json with the default"
echo "profile. Try 'cfscan --quick --dry-run' to see the scanner command"
echo "without running anything."
